apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app
  # namespace: 1-example
spec:
  selector:
    matchLabels:
      app: platform-app
  replicas: 2
  template:
    metadata:
      labels:
        app: platform-app
    spec:
      containers:
      - name: platform-app
        image: 417805623903.dkr.ecr.ap-southeast-2.amazonaws.com/beequantapp:v0.0.7
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_DEV_SERVER_URL
          value: "https://beequantai.net/graphql"
        - name: NEXT_PUBLIC_THIRD_PARTY_API_URL
          value: "https://beequantai.net/auth"
---
apiVersion: v1
kind: Service
metadata:
  name: platform-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: alb
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  # namespace: 1-example
spec:
  ports:
  - port: 443
    targetPort: 3000
    protocol: TCP
  type: NodePort
  selector:
    app: platform-app
